// frontend/abi.js
export const SHIPMENT_REGISTRY_ABI = [
  "constructor()",
  "error EnforcedPause()",
  "error ExpectedPause()",
  "error OwnableInvalidOwner(address owner)",
  "error OwnableUnauthorizedAccount(address account)",
  "error ReentrancyGuardReentrantCall()",
  "event DocumentAnchored(string indexed id, string docHash, address indexed anchoredBy, uint256 timestamp)",
  "event HandlerAuthorized(address indexed handler, address indexed by)",
  "event HandlerRevoked(address indexed handler, address indexed by)",
  "event HandoffRecorded(string indexed id, address indexed handler, string location, uint256 temperature, string imageHash, uint256 timestamp)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event Paused(address account)",
  "event ShipmentCreated(string indexed id, string product, address indexed creator, uint256 timestamp)",
  "event ShipmentFinalized(string indexed id, address indexed finalizedBy, uint256 timestamp)",
  "event Unpaused(address account)",
  "event VendorAuthorized(address indexed vendor, address indexed by)",
  "event VendorRevoked(address indexed vendor, address indexed by)",
  "function anchorDocument(string id, string docHash)",
  "function authorizeHandler(address handler)",
  "function authorizeVendor(address vendor)",
  "function authorizedHandlers(address) view returns (bool)",
  "function authorizedVendors(address) view returns (bool)",
  "function createShipment(string id, string product)",
  "function finalizeShipment(string id)",
  "function getAllHandoffs(string id) view returns (tuple(address handler, string location, uint256 temperature, string imageHash, uint256 timestamp)[])",
  "function getHandoff(string id, uint256 index) view returns (address handler, string location, uint256 temperature, string imageHash, uint256 timestamp)",
  "function getShipment(string id) view returns (string id_, string product, address creator, bool finalized, string documentHash, uint256 handoffCount)",
  "function owner() view returns (address)",
  "function pause()",
  "function paused() view returns (bool)",
  "function recordHandoff(string id, string location, uint256 temperature, string imageHash)",
  "function renounceOwnership()",
  "function revokeHandler(address handler)",
  "function revokeVendor(address vendor)",
  "function shipmentExistsCheck(string id) view returns (bool)",
  "function totalShipments() view returns (uint256)",
  "function transferOwnership(address newOwner)",
  "function unpause()"
];

export const TRUST_CHAIN_ACL_ABI = [
  "constructor(address admin)",
  "error AccessControlBadConfirmation()",
  "error AccessControlUnauthorizedAccount(address account, bytes32 neededRole)",
  "error EnforcedPause()",
  "error ExpectedPause()",
  "event Paused(address account)",
  "event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)",
  "event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)",
  "event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)",
  "event Unpaused(address account)",
  "function AUDITOR_ROLE() view returns (bytes32)",
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
  "function HANDLER_ROLE() view returns (bytes32)",
  "function getRoleAdmin(bytes32 role) view returns (bytes32)",
  "function grantRole(bytes32 role, address account)",
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function pause()",
  "function paused() view returns (bool)",
  "function renounceRole(bytes32 role, address callerConfirmation)",
  "function revokeRole(bytes32 role, address account)",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "function unpause()"
];
