/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ShipmentRegistry {
      
    export type HandoffStruct = {handler: AddressLike, location: string, temperature: BigNumberish, imageHash: string, timestamp: BigNumberish}

    export type HandoffStructOutput = [handler: string, location: string, temperature: bigint, imageHash: string, timestamp: bigint] & {handler: string, location: string, temperature: bigint, imageHash: string, timestamp: bigint }
  
    }

  export interface ShipmentRegistryInterface extends Interface {
    getFunction(nameOrSignature: "anchorDocument" | "authorizeHandler" | "authorizedHandlers" | "createShipment" | "finalizeShipment" | "getAllHandoffs" | "getHandoff" | "getShipment" | "owner" | "pause" | "paused" | "recordHandoff" | "renounceOwnership" | "revokeHandler" | "shipmentExistsCheck" | "totalShipments" | "transferOwnership" | "unpause"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DocumentAnchored" | "HandlerAuthorized" | "HandlerRevoked" | "HandoffRecorded" | "OwnershipTransferred" | "Paused" | "ShipmentCreated" | "ShipmentFinalized" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'anchorDocument', values: [string, string]): string;
encodeFunctionData(functionFragment: 'authorizeHandler', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'authorizedHandlers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'createShipment', values: [string, string]): string;
encodeFunctionData(functionFragment: 'finalizeShipment', values: [string]): string;
encodeFunctionData(functionFragment: 'getAllHandoffs', values: [string]): string;
encodeFunctionData(functionFragment: 'getHandoff', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getShipment', values: [string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordHandoff', values: [string, string, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokeHandler', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'shipmentExistsCheck', values: [string]): string;
encodeFunctionData(functionFragment: 'totalShipments', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'anchorDocument', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizeHandler', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedHandlers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createShipment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeShipment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllHandoffs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getHandoff', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getShipment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordHandoff', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeHandler', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shipmentExistsCheck', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalShipments', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
  }

  
    export namespace DocumentAnchoredEvent {
      export type InputTuple = [id: string, docHash: string, anchoredBy: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [id: string, docHash: string, anchoredBy: string, timestamp: bigint];
      export interface OutputObject {id: string, docHash: string, anchoredBy: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HandlerAuthorizedEvent {
      export type InputTuple = [handler: AddressLike, by: AddressLike];
      export type OutputTuple = [handler: string, by: string];
      export interface OutputObject {handler: string, by: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HandlerRevokedEvent {
      export type InputTuple = [handler: AddressLike, by: AddressLike];
      export type OutputTuple = [handler: string, by: string];
      export interface OutputObject {handler: string, by: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HandoffRecordedEvent {
      export type InputTuple = [id: string, handler: AddressLike, location: string, temperature: BigNumberish, imageHash: string, timestamp: BigNumberish];
      export type OutputTuple = [id: string, handler: string, location: string, temperature: bigint, imageHash: string, timestamp: bigint];
      export interface OutputObject {id: string, handler: string, location: string, temperature: bigint, imageHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ShipmentCreatedEvent {
      export type InputTuple = [id: string, product: string, creator: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [id: string, product: string, creator: string, timestamp: bigint];
      export interface OutputObject {id: string, product: string, creator: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ShipmentFinalizedEvent {
      export type InputTuple = [id: string, finalizedBy: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [id: string, finalizedBy: string, timestamp: bigint];
      export interface OutputObject {id: string, finalizedBy: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ShipmentRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ShipmentRegistry;
    waitForDeployment(): Promise<this>;

    interface: ShipmentRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    anchorDocument: TypedContractMethod<
      [id: string, docHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    authorizeHandler: TypedContractMethod<
      [handler: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    authorizedHandlers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    createShipment: TypedContractMethod<
      [id: string, product: string, ],
      [void],
      'nonpayable'
    >
    

    
    finalizeShipment: TypedContractMethod<
      [id: string, ],
      [void],
      'nonpayable'
    >
    

    
    getAllHandoffs: TypedContractMethod<
      [id: string, ],
      [ShipmentRegistry.HandoffStructOutput[]],
      'view'
    >
    

    
    getHandoff: TypedContractMethod<
      [id: string, index: BigNumberish, ],
      [[string, string, bigint, string, bigint] & {handler: string, location: string, temperature: bigint, imageHash: string, timestamp: bigint }],
      'view'
    >
    

    
    getShipment: TypedContractMethod<
      [id: string, ],
      [[string, string, string, boolean, string, bigint] & {id_: string, product: string, creator: string, finalized: boolean, documentHash: string, handoffCount: bigint }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    recordHandoff: TypedContractMethod<
      [id: string, location: string, temperature: BigNumberish, imageHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    revokeHandler: TypedContractMethod<
      [handler: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    shipmentExistsCheck: TypedContractMethod<
      [id: string, ],
      [boolean],
      'view'
    >
    

    
    totalShipments: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'anchorDocument'): TypedContractMethod<
      [id: string, docHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authorizeHandler'): TypedContractMethod<
      [handler: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authorizedHandlers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'createShipment'): TypedContractMethod<
      [id: string, product: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalizeShipment'): TypedContractMethod<
      [id: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllHandoffs'): TypedContractMethod<
      [id: string, ],
      [ShipmentRegistry.HandoffStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getHandoff'): TypedContractMethod<
      [id: string, index: BigNumberish, ],
      [[string, string, bigint, string, bigint] & {handler: string, location: string, temperature: bigint, imageHash: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getShipment'): TypedContractMethod<
      [id: string, ],
      [[string, string, string, boolean, string, bigint] & {id_: string, product: string, creator: string, finalized: boolean, documentHash: string, handoffCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'recordHandoff'): TypedContractMethod<
      [id: string, location: string, temperature: BigNumberish, imageHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeHandler'): TypedContractMethod<
      [handler: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'shipmentExistsCheck'): TypedContractMethod<
      [id: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalShipments'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DocumentAnchored'): TypedContractEvent<DocumentAnchoredEvent.InputTuple, DocumentAnchoredEvent.OutputTuple, DocumentAnchoredEvent.OutputObject>;
getEvent(key: 'HandlerAuthorized'): TypedContractEvent<HandlerAuthorizedEvent.InputTuple, HandlerAuthorizedEvent.OutputTuple, HandlerAuthorizedEvent.OutputObject>;
getEvent(key: 'HandlerRevoked'): TypedContractEvent<HandlerRevokedEvent.InputTuple, HandlerRevokedEvent.OutputTuple, HandlerRevokedEvent.OutputObject>;
getEvent(key: 'HandoffRecorded'): TypedContractEvent<HandoffRecordedEvent.InputTuple, HandoffRecordedEvent.OutputTuple, HandoffRecordedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'ShipmentCreated'): TypedContractEvent<ShipmentCreatedEvent.InputTuple, ShipmentCreatedEvent.OutputTuple, ShipmentCreatedEvent.OutputObject>;
getEvent(key: 'ShipmentFinalized'): TypedContractEvent<ShipmentFinalizedEvent.InputTuple, ShipmentFinalizedEvent.OutputTuple, ShipmentFinalizedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'DocumentAnchored(string,string,address,uint256)': TypedContractEvent<DocumentAnchoredEvent.InputTuple, DocumentAnchoredEvent.OutputTuple, DocumentAnchoredEvent.OutputObject>;
      DocumentAnchored: TypedContractEvent<DocumentAnchoredEvent.InputTuple, DocumentAnchoredEvent.OutputTuple, DocumentAnchoredEvent.OutputObject>;
    

      'HandlerAuthorized(address,address)': TypedContractEvent<HandlerAuthorizedEvent.InputTuple, HandlerAuthorizedEvent.OutputTuple, HandlerAuthorizedEvent.OutputObject>;
      HandlerAuthorized: TypedContractEvent<HandlerAuthorizedEvent.InputTuple, HandlerAuthorizedEvent.OutputTuple, HandlerAuthorizedEvent.OutputObject>;
    

      'HandlerRevoked(address,address)': TypedContractEvent<HandlerRevokedEvent.InputTuple, HandlerRevokedEvent.OutputTuple, HandlerRevokedEvent.OutputObject>;
      HandlerRevoked: TypedContractEvent<HandlerRevokedEvent.InputTuple, HandlerRevokedEvent.OutputTuple, HandlerRevokedEvent.OutputObject>;
    

      'HandoffRecorded(string,address,string,uint256,string,uint256)': TypedContractEvent<HandoffRecordedEvent.InputTuple, HandoffRecordedEvent.OutputTuple, HandoffRecordedEvent.OutputObject>;
      HandoffRecorded: TypedContractEvent<HandoffRecordedEvent.InputTuple, HandoffRecordedEvent.OutputTuple, HandoffRecordedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'ShipmentCreated(string,string,address,uint256)': TypedContractEvent<ShipmentCreatedEvent.InputTuple, ShipmentCreatedEvent.OutputTuple, ShipmentCreatedEvent.OutputObject>;
      ShipmentCreated: TypedContractEvent<ShipmentCreatedEvent.InputTuple, ShipmentCreatedEvent.OutputTuple, ShipmentCreatedEvent.OutputObject>;
    

      'ShipmentFinalized(string,address,uint256)': TypedContractEvent<ShipmentFinalizedEvent.InputTuple, ShipmentFinalizedEvent.OutputTuple, ShipmentFinalizedEvent.OutputObject>;
      ShipmentFinalized: TypedContractEvent<ShipmentFinalizedEvent.InputTuple, ShipmentFinalizedEvent.OutputTuple, ShipmentFinalizedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }